version: '3'
services:
    # Back
    php8:
        image: symfony
        container_name: sf
        restart: always
        build: ./project/backend
        ports:
            - "9000:8000"
        volumes:
            - ./project/backend:/var/www/html

    db:
        image: mariadb
        container_name: mdb
        restart: always
        #volumes:
        #    - db-data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: dev
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db


    # Front
    angular-service:
        container_name: ng
        restart: always
        ports:
            - "4300:4200" 
        build: ./project/frontend
        volumes:
            - './project/frontend:/usr/src/app'

#volumes:
#    db-data:

